version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: [ '9200:9200' ]
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'